"""Migración inicial

Revision ID: 460ce6a67657
Revises: 
Create Date: 2025-05-18 22:28:09.628536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '460ce6a67657'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('huertos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('ubicacion', sa.String(length=200), nullable=True),
    sa.Column('superficie_ha', sa.Float(), nullable=True),
    sa.Column('tipo_cultivo', sa.String(length=100), nullable=True),
    sa.Column('fecha_siembra', sa.Date(), nullable=True),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['responsable_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recomendacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('adjunto', sa.String(length=200), nullable=True),
    sa.Column('tecnico_id', sa.Integer(), nullable=True),
    sa.Column('autor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actividad_huerto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('huerto_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('responsable', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('producto', sa.String(length=100), nullable=True),
    sa.Column('dosis', sa.String(length=50), nullable=True),
    sa.Column('plaga', sa.String(length=100), nullable=True),
    sa.Column('nivel_infestacion', sa.String(length=20), nullable=True),
    sa.Column('resultado', sa.Text(), nullable=True),
    sa.Column('fotos', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['huerto_id'], ['huertos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bodegas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('ubicacion', sa.String(length=200), nullable=True),
    sa.Column('huerto_id', sa.Integer(), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['huerto_id'], ['huertos.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('formulario_tarea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('huerto_id', sa.Integer(), nullable=True),
    sa.Column('bodega_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bodega_id'], ['bodegas.id'], ),
    sa.ForeignKeyConstraint(['huerto_id'], ['huertos.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quimicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('cantidad_litros', sa.Float(), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=True),
    sa.Column('bodega_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bodega_id'], ['bodegas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tecnico_bodega',
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('bodega_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bodega_id'], ['bodegas.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('tecnico_id', 'bodega_id')
    )
    op.create_table('checklist_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('realizado', sa.Boolean(), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('formulario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['formulario_id'], ['formulario_tarea.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checklist_item')
    op.drop_table('tecnico_bodega')
    op.drop_table('quimicos')
    op.drop_table('formulario_tarea')
    op.drop_table('bodegas')
    op.drop_table('actividad_huerto')
    op.drop_table('recomendacion')
    op.drop_table('huertos')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
