"""Crear tabla contacts

Revision ID: 60f6c578e305
Revises: 
Create Date: 2025-08-11 23:06:52.328170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60f6c578e305'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('activity_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('fill_color', sa.String(length=20), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'key', name='uq_activity_type_empresa_key')
    )
    with op.batch_alter_table('activity_type', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_type_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'email', name='uq_user_email_empresa')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('audio_mensaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('archivo', sa.String(length=255), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audio_mensaje', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audio_mensaje_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('huertos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('ubicacion', sa.String(length=200), nullable=True),
    sa.Column('superficie_ha', sa.Float(), nullable=True),
    sa.Column('tipo_cultivo', sa.String(length=120), nullable=True),
    sa.Column('fecha_siembra', sa.Date(), nullable=True),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.Column('center_lat', sa.Float(), nullable=True),
    sa.Column('center_lng', sa.Float(), nullable=True),
    sa.Column('bounds_geojson', sa.Text(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('huertos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_huertos_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('actividad_huerto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('huerto_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('responsable', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('producto', sa.String(length=100), nullable=True),
    sa.Column('dosis', sa.String(length=50), nullable=True),
    sa.Column('plaga', sa.String(length=100), nullable=True),
    sa.Column('nivel_infestacion', sa.String(length=20), nullable=True),
    sa.Column('resultado', sa.Text(), nullable=True),
    sa.Column('fotos', sa.String(length=250), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['huerto_id'], ['huertos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actividad_huerto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actividad_huerto_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_actividad_huerto_huerto_id'), ['huerto_id'], unique=False)

    op.create_table('bodegas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('ubicacion', sa.String(length=200), nullable=True),
    sa.Column('huerto_id', sa.Integer(), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['huerto_id'], ['huertos.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bodegas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bodegas_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mimetype', sa.String(length=120), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('huerto_id', sa.Integer(), nullable=True),
    sa.Column('subido_por_id', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['huerto_id'], ['huertos.id'], ),
    sa.ForeignKeyConstraint(['subido_por_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documentos_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('parcelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('huerto_id', sa.Integer(), nullable=False),
    sa.Column('geom_geojson', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['huerto_id'], ['huertos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parcelas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parcelas_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('recomendacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('adjunto', sa.String(length=200), nullable=True),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('autor_id', sa.Integer(), nullable=False),
    sa.Column('huerto_id', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['huerto_id'], ['huertos.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recomendacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recomendacion_autor_id'), ['autor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recomendacion_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recomendacion_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_recomendacion_huerto_id'), ['huerto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recomendacion_tecnico_id'), ['tecnico_id'], unique=False)

    op.create_table('actividades_campo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('huerto_id', sa.Integer(), nullable=False),
    sa.Column('parcela_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=80), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('ruta_geojson', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('duracion_min', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['huerto_id'], ['huertos.id'], ),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('actividades_campo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_actividades_campo_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('formulario_tarea',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('huerto_id', sa.Integer(), nullable=True),
    sa.Column('bodega_id', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bodega_id'], ['bodegas.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['huerto_id'], ['huertos.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('formulario_tarea', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_formulario_tarea_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('quimicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('cantidad_litros', sa.Float(), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=True),
    sa.Column('bodega_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bodega_id'], ['bodegas.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quimicos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quimicos_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('tecnico_bodega',
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('bodega_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bodega_id'], ['bodegas.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('tecnico_id', 'bodega_id')
    )
    op.create_table('checklist_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('realizado', sa.Boolean(), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('formulario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['formulario_id'], ['formulario_tarea.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checklist_item')
    op.drop_table('tecnico_bodega')
    with op.batch_alter_table('quimicos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quimicos_empresa_id'))

    op.drop_table('quimicos')
    with op.batch_alter_table('formulario_tarea', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_formulario_tarea_empresa_id'))

    op.drop_table('formulario_tarea')
    with op.batch_alter_table('actividades_campo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actividades_campo_empresa_id'))

    op.drop_table('actividades_campo')
    with op.batch_alter_table('recomendacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recomendacion_tecnico_id'))
        batch_op.drop_index(batch_op.f('ix_recomendacion_huerto_id'))
        batch_op.drop_index(batch_op.f('ix_recomendacion_fecha'))
        batch_op.drop_index(batch_op.f('ix_recomendacion_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_recomendacion_autor_id'))

    op.drop_table('recomendacion')
    with op.batch_alter_table('parcelas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parcelas_empresa_id'))

    op.drop_table('parcelas')
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documentos_empresa_id'))

    op.drop_table('documentos')
    with op.batch_alter_table('bodegas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bodegas_empresa_id'))

    op.drop_table('bodegas')
    with op.batch_alter_table('actividad_huerto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_actividad_huerto_huerto_id'))
        batch_op.drop_index(batch_op.f('ix_actividad_huerto_empresa_id'))

    op.drop_table('actividad_huerto')
    with op.batch_alter_table('huertos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_huertos_empresa_id'))

    op.drop_table('huertos')
    with op.batch_alter_table('audio_mensaje', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audio_mensaje_empresa_id'))

    op.drop_table('audio_mensaje')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('activity_type', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_type_empresa_id'))

    op.drop_table('activity_type')
    op.drop_table('empresas')
    # ### end Alembic commands ###
